apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-synapse-configs
  namespace: keshi
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi