apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  namespace: keshi
  labels:
    name: apim-mysql
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/test/mysql"