apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apimanagers.apim.wso2.com
spec:
  group: apim.wso2.com
  version: v1alpha1
  names:
    kind: APIManager
    plural: apimanagers
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Spec
      type: string
      description: The cron spec defining the interval a CronJob is run
      jsonPath: .spec.cronSpec
    - name: Replicas
      type: integer
      description: The number of jobs launched by the CronJob
      jsonPath: .spec.replicas
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    
